### ISSUE TITLE
Section: States And Effects

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/top-meta#197]
#### Section Summary

1. Explain what state entails, and when would a React component require state. This should impart to the learners that state can be inferred as a component’s “memory”. Explain that React components have the ability to rerender (get destroyed and instantiated again) based on changes in their state.
2. Get into hands-on examples with using the useState hook to set and update state. These examples should cover simple state variables to complex ones, like arrays and objects. This should be a comprehensive guide on how to update array/object states without mutation. Learners should know and understand that state should be treated as immutable.
3. Comprehensively explain how to decide and structure state. Go into use cases where state is superfluous and not needed. Go into use cases where there exists redundant state variables. Describe what lifting state up means with an example. By this point, learners should be able to make wise decisions regarding their state.
4. Controlled components (???)
5. Explain that state is stored inside of React rather than components themselves. State is essentially tied to the position of the component in the Virtual DOM. Virtual DOM is an in-memory representation of the DOM. This should also mention the “The Key to React” lesson of the “Getting Started With React” section.

#### Section Lessons

1. Introduction To State
2. More On State
3. Project: CV Application
4. Pure Components And Side Effects
5. How To Deal With Side Effects 
6. Project: Memory Card

**Comment by thatblindgeye** [comment]
Section Summary
1 and 3: I feel like 3's content of "Go into use cases where state is superfluous and not needed. Go into use cases where there exists redundant state variables" could just be placed into 1's content of "when would a React component require state", but either way not sure if it should be something gone into too much detail. Having 3's content be more about lifting state up, with 1 being more about state "basics" (like when and when not to use it) essentially.

4: I think it'd be worth having a lesson on controlled vs uncontrolled components, but I'm not sure if it'd be better after users learn about refs (if they do; haven't read other section lessons yet). We could also cover controlled components now, explain the difference between them and uncontrolled, then go into uncontrolled in another lesson.

5: Not sure if this is ordered last because it would come in a later lesson in the section, but I think this could be tied to 1's content as well, depending how long the lesson would be.

Section Lessons
2. Depending what the final content ends up being, maybe a more descriptive lesson title if we can

4 and 5: What exactly would these lessons cover in the context of a "state and effects" section? How would it pertain to the other content in the section?

**Comment by mgrigoriev8109** [comment]
@01zulfi @thatblindgeye In the current State and Props lesson https://www.theodinproject.com/lessons/node-path-javascript-state-and-props#additional-resources , this Thinking In React article https://reactjs.org/docs/thinking-in-react.html is mentioned as an Additional Resource. I think this article and what it tries to convey in terms of an incremental process can be very helpful - in making the subsequent project easier to implement, having more to talk about during interviews, and possibly lowering the number of questions we see in #react-help. 

In this project's discord channel steve mentions using it early on / in the Introduction to React lesson https://discordapp.com/channels/505093832157691914/1009352959970267146/1011337807882633286

Personally, I think it might be a bit premature that early on, partly as learners would forget a good amount of the thought process that goes behind planning a React project and partly because it relies on some understanding of Props and State. 

So I think there could be value in inserting *something* regarding thinking in react in this section, possibly either directly linking this article inside the CV Project itself as one of the first steps of that project, or possibly as a small additional lesson between More On State and the CV Application. (I could see the second one having a bit more value at the cost of adding yet another lesson, and taking up time to create / review)

I'd love to hear your thoughts on this, as I have 0 real-world experience in React and very little actual React experience so this could be a horrible idea.
